### ISSUE TITLE
Streams under 1 Mbps don't work properly

### ISSUE THREAD

**Issue by JoshNotWright** [nwithan8/tauticord#16]
When a stream under 1 Mbps is by itself, it doesn't add to the total stream count. When there are other streams playing concurrently, it will add the low bitrate stream to the total stream count, but it won't display it in the message. It simply skips over it
![image (2)](https://user-images.githubusercontent.com/17754256/133189471-f380778e-50b0-4cb9-9566-4d4420d4b520.png)

**Comment by nwithan8** [comment]
> Hello,
> 
> Same issue with my users watching Live TV through DVR (HdHomeRun) Thanks in advance!

Fixed in 3fd6c9290454de9a8347ded1fc416bb32f701210

**Comment by NeZios** [comment]
> > Hello,
> > Same issue with my users watching Live TV through DVR (HdHomeRun) Thanks in advance!
> 
> Fixed in [3fd6c92](https://github.com/nwithan8/tauticord/commit/3fd6c9290454de9a8347ded1fc416bb32f701210)

I still have the problem in the latest version of the docker build.

**Comment by nwithan8** [comment]
Are there any error logs? It looks like Tauticord picked up that there were four streams based on the termination emojis.

**Comment by NeZios** [comment]
Here's the logs of my Tauticord docker

[suspicious_stonebraker-2022-01-25T15-55-31.log.gz](https://github.com/nwithan8/tauticord/files/7935073/suspicious_stonebraker-2022-01-25T15-55-31.log.gz)

**Comment by nwithan8** [comment]
If you could try the bot out and report back to me, that would be great. My personal live TV setup is not set up yet, so I can't test this myself unfortunately.

**Comment by JoshNotWright** [comment]
![Capture](https://user-images.githubusercontent.com/17754256/151682977-5ce5d46b-c37c-4e49-95e0-181688645b6d.PNG)

After updating, all streams disappeared. The counter also says zero, but interestingly the reactions are correct. Before I took the screenshot there were two streams, and two reactions on the message.

**Comment by nwithan8** [comment]
Are the logs reporting any errors? I'm trying to confirm when in the logic it's failing.

**Comment by NeZios** [comment]
Hello, after updating to today's latest update, I have the same problem as  @JoshNotWright 
Here is a screenshot with 4 streams : 
<img width="333" alt="Capture d’écran 2022-02-01 à 22 45 54" src="https://user-images.githubusercontent.com/38002539/152057103-4334a4f1-cb90-494a-baa0-a70b4736b536.png">

Here's the log : 
`today at 22:43:02WARNING:PyNaCl is not installed, voice will NOT be supported
today at 22:43:06WARNING:We are being rate limited. Retrying in 0.09 seconds. Handled under the bucket "933480494606221382:None:/channels/{channel_id}/messages/{message_id}/reactions/{emoji}/@me"
today at 22:47:41WARNING:We are being rate limited. Retrying in 325.17 seconds. Handled under the bucket "933479351763226674:None:/channels/{channel_id}"`
